version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/demo-repo
hooks:
  Install:
    - location: ~/demo-repo/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ~/demo-repo/scripts/start_server.sh
      timeout: 300
      runas: root
  